"""Add energy-related fields to StateCount table

Revision ID: b54cb1a8c96a
Revises: d5ac7b3e1e79
Create Date: 2024-11-30 21:30:08.870222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54cb1a8c96a'
down_revision = 'd5ac7b3e1e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_count', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewable', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('solar', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wind', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hydro', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nuclear', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('coal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('petroleum', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('state_count', schema=None) as batch_op:
        batch_op.drop_column('petroleum')
        batch_op.drop_column('gas')
        batch_op.drop_column('coal')
        batch_op.drop_column('nuclear')
        batch_op.drop_column('hydro')
        batch_op.drop_column('wind')
        batch_op.drop_column('solar')
        batch_op.drop_column('renewable')

    # ### end Alembic commands ###
